### Test the signup endpoint
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john1@example.com",
  "password": "password123",
  "phone": "+1234567890",
  "latitude": 40.7128,
  "longitude": -74.0060,
  "role": "volunteer",
  "skills": ["medical", "rescue"]
}

### Test the login endpoint for a wrong password
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "gov.official@example.com",
  "password": "securepassword"
}

### Test the login endpoint for a correct password
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "password123"
}

### test routes authentification
GET http://localhost:8000/gov/dashboard

### Test token verification
GET http://localhost:8000/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5MWIyMDllMy0wYjU4LTRhZjUtODFjNy1kY2E5OWE3NGU2NTQiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJyb2xlIjoidm9sdW50ZWVyIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzQ4MDMyNjUxfQ.PIkEpPEfRaRK7augznEVjYYmH2141MBhQkE6N1ePUtE


### Test getting user profile
GET http://localhost:8000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5MWIyMDllMy0wYjU4LTRhZjUtODFjNy1kY2E5OWE3NGU2NTQiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJyb2xlIjoidm9sdW50ZWVyIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzQ4MDMyNjUxfQ.PIkEpPEfRaRK7augznEVjYYmH2141MBhQkE6N1ePUtE
