### Volunteer Signup
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
  "name": "John Volunteer",
  "email": "john.volunteer@example.com",
  "password": "securepass123",
  "phone": "+1234567890",
  "latitude": 40.7128,
  "longitude": -74.0060,
  "role": "volunteer",
  "skills": ["first aid", "rescue"]
}

### First Responder Signup
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
  "name": "Alice Responder",
  "email": "alice@police.org",
  "password": "securepass123",
  "phone": "+1987654321",
  "latitude": 34.0522,
  "longitude": -118.2437,
  "role": "first_responder",
  "department": "Emergency Services",
  "unit": "Fire Department"
}

### Government Signup
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
  "name": "Gov Officer",
  "email": "officer@ministry.gov",
  "password": "securepass123",
  "phone": "+1122334455",
  "latitude": 38.9072,
  "longitude": -77.0369,
  "role": "government",
  "department": "Disaster Management",
  "position": "Coordinator"
}

### General User Signup
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
  "name": "Regular User",
  "email": "user@example.com",
  "password": "securepass123",
  "phone": "+1010101010",
  "latitude": 37.7749,
  "longitude": -122.4194,
  "role": "user"
}


### Test the login endpoint for a wrong password
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "gov.official@example.com",
  "password": "securepassword",
  "latitude": 40.7128,
  "longitude": -74.0060,
}

### Test the login endpoint for a correct password
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "securepass123",
  "latitude": 37.7749,
  "longitude": -122.4194
}

### test routes authentification
GET http://localhost:8000/gov/dashboard

### Test token verification
GET http://localhost:8000/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5MWIyMDllMy0wYjU4LTRhZjUtODFjNy1kY2E5OWE3NGU2NTQiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJyb2xlIjoidm9sdW50ZWVyIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzQ4MDMyNjUxfQ.PIkEpPEfRaRK7augznEVjYYmH2141MBhQkE6N1ePUtE


### Test getting user profile
GET http://localhost:8000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5MWIyMDllMy0wYjU4LTRhZjUtODFjNy1kY2E5OWE3NGU2NTQiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJyb2xlIjoidm9sdW50ZWVyIiwibmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzQ4MDMyNjUxfQ.PIkEpPEfRaRK7augznEVjYYmH2141MBhQkE6N1ePUtE
